name: Build Next JS App

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  Build:
    name: Build Next.js app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ">=18.17.0" # FIX version

      - name: Install dependencies
        run: npm install
        working-directory: ./app

      - name: Build Next.js app
        run: npm run export
        working-directory: ./app

      - name: Save build artifacts
        uses: actions/upload-artifact@v4.3.2
        with:
          name: next-static
          path: ./app/out
    
  Git-Pages:
    name: Deploy to GitHub Pages
    needs: Build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4.1.5
        with:
          name: next-static
          path: ./app
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./app
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  
  Push-EC2:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Step 1
        run: echo "This is a manual job"


