name: Print

on:
  push:
    branches:
      - main

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run script file
        run: |
          chmod +x ./run.sh
          ./run.sh
        shell: bash