name: Print

on:
  push:
    branches:
      - main

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Print code
        run: |
          ls -la
          chmod +x ./run.sh
          ./run.sh
        shell: bash