name: Upload File to AWS

on:
  workflow_dispatch:

jobs:
  Upload:
    name: Upload file to AWS EC2
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact site
        uses: actions/download-artifact@v4
        with:
          name: Site-FILES
          path: distfiles

      - name: Download artifact ip
        uses: actions/download-artifact@v4
        with:
          name: public_ip
          path: .

      - name: Get Public IP
        run: echo "HOST=$(cat public_ip.txt)" >> $GITHUB_ENV

      - name: Upload file to AWS EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.HOST }}
          username: "ubuntu"
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: distfiles/
          target: /var/www/html/