name: Upload File to AWS

on:
  workflow_dispatch:

jobs:
  Upload:
    name: Upload file to AWS EC2
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact public_ip
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          path: .

      - name: Download artifact site
        uses: actions/download-artifact@v4.1.5
        with:
          name: Site-FILES
          github-token: ${{ secrets.GIT_KEY }}
          repository: voutuk/Next.js-Build-Push
          run-id: 0001
          path: distfiles

      - name: Get Public IP
        run: echo "HOST=$(cat public_ip.txt)" >> $GITHUB_ENV

      - name: Upload file to AWS EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.HOST }}
          username: "ubuntu"
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: distfiles/
          target: /var/www/html/