name: Public dev github pages

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ">=18.17.0" # FIX version

      - name: Install dependencies
        run: npm install
        working-directory: ./app

      - name: Build Next.js app
        run: npm run export
        working-directory: ./app

      - name: Save build artifacts
        uses: actions/upload-artifact@v4.3.2
        with:
          name: build-artifacts
          path: ./app/out

      - name: Deploy to AWS
        run: |
          aws s3 sync app/out/ s3://$BUCKET_NAME
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"