name: Push app to AWS Server

on:
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
            - name: Checkout code
            uses: actions/checkout@v2

            - name: Set up AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Install AWS CLI
                run: |
                    sudo apt-get update
                    sudo apt-get install -y awscli

            - name: Push artifact to EC2 server
                run: |
                    aws s3 cp path/to/artifact s3://your-bucket-name
                    aws ec2 run-instances --image-id ami-xxxxxxxx --instance-type t2.micro --key-name your-key-pair-name --security-group-ids your-security-group-id --subnet-id your-subnet-id --user-data 'sudo apt-get update && sudo apt-get install -y apache2 && sudo systemctl start apache2'